//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kart
    {
        public int KartId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Durum { get; set; }
        public string İs { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TeknikId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
    
        public virtual Tbl_Teknik Tbl_Teknik { get; set; }
    }
}
