//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanici
    {
        public int KullaniciId { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public string Email { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> Teknikid { get; set; }
    
        public virtual Tbl_Teknik Tbl_Teknik { get; set; }
    }
}
