//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Teknik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Teknik()
        {
            this.Tbl_Kart = new HashSet<Tbl_Kart>();
            this.Tbl_Kullanici = new HashSet<Tbl_Kullanici>();
        }
    
        public int TeknikId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> KartNo { get; set; }
        public string ProjeAdi { get; set; }
        public string TeknikUzman { get; set; }
        public Nullable<int> TahminiSure { get; set; }
        public Nullable<int> GecenSure { get; set; }
        public string Aciklama { get; set; }
        public string Notlar { get; set; }
        public Nullable<int> KullaniciId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kart> Tbl_Kart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kullanici> Tbl_Kullanici { get; set; }
    }
}
