//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Start
    {
        public int StartId { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public string Turu { get; set; }
    }
}
